// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using User.Infrastructure;

namespace User.API.Infrastructure.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20200207101423_initdatabase")]
    partial class initdatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("User.Domain.AggregatesModel.UserAggregates.Entitys.UserInformation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("createtime");

                    b.Property<int?>("statusId");

                    b.Property<DateTime>("updateTime");

                    b.HasKey("Id");

                    b.HasIndex("statusId");

                    b.ToTable("UserInformation");
                });

            modelBuilder.Entity("User.Domain.AggregatesModel.UserAggregates.Entitys.UserStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("UserStatus");
                });

            modelBuilder.Entity("User.Domain.AggregatesModel.UserAggregates.Entitys.UserInformation", b =>
                {
                    b.HasOne("User.Domain.AggregatesModel.UserAggregates.Entitys.UserStatus", "status")
                        .WithMany()
                        .HasForeignKey("statusId");
                });
#pragma warning restore 612, 618
        }
    }
}
